kind: pipeline
type: docker
name: deploy notodo

trigger:
  branch: [master, dev]
  event: [push]

clone:
  retries: 3
  depth: 1

environment:
  GOPROXY: https://goproxy.cn

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: test
    image: golang:1.20-alpine
    commands:
      - go test -v ./...

  - name: deploy prod
    when:
        branch: master
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      MONGO_URI:
        from_secret: mongo_uri
    commands:
      - cd ..
      - cp src notodo
      - cd notodo
      - docker compose build notodo
      - docker compose up -d --no-deps

  - name: deploy dev
    when:
        branch: dev
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      MONGO_URI:
        from_secret: mongo_uri
    commands:
      - cd ..
      - cp src notodo-dev
      - cd notodo-dev
      - docker compose build notodo
      - docker compose -f docker-compose.dev.yml up -d --no-deps
