version: "3.9"
services:
  notodo:
    container_name: notodo
    build:
      context: .
      args:
        - GOPROXY=${GOPROXY}
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - "8888:8888"
